import Head from 'next/head';
import Login from '../components/Login';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Gossip | Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap"
                    rel="stylesheet"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <Login />
        </div>
    );
}
